config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  get "/report" => "reports#report", as: :report
  
  resources :categories, except: [ :show ]
  resources :expenses,   except: [ :show ]
  resources :incomes,    except: [ :show ]
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :incomes,  dependent: :destroy
  has_many :expenses, dependent: :destroy
  
  validates_presence_of :name

  def name=(val)
    write_attribute(:name, val.upcase)
  end
    
  def self.categories_names
    all.map(&:name)
  end
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  
  validates_presence_of :sum, :category, :date
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates_presence_of :sum, :category, :date
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :trackable, 
         :validatable
  
  has_many :expenses,   dependent: :destroy
  has_many :incomes,    dependent: :destroy
  has_many :categories, dependent: :destroy
  
  def add_category(category)
    categories << category
  end
  
  def build_category_if_not_exists(name)
    categories.where(name: name.upcase).first_or_create
  end
  
  def filter_incomes(category_id, start_date, end_date)
    if category_id.present?
      incomes.where("category_id = ? and date >= ? and date <= ?", category_id, start_date, end_date)
    else
      incomes.where("date >= ? and date <= ?", start_date, end_date)
    end
  end
  
  def filter_expenses(category_id, start_date, end_date)
    if category_id.present?
      expenses.where("category_id = ? and date >= ? and date <= ?", category_id, start_date, end_date)
    else
      expenses.where("date >= ? and date <= ?", start_date, end_date)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories.all
  end

  def create
    @category = current_user.build_category_if_not_exists(category_params[:name])
      
      if @category.save
        redirect_to categories_path
      else
        flash[:alert] = "Enter category name please"
        render :new
      end
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    
    if @category.update(category_params)
      redirect_to categories_path
    else
      flash[:alert] = "Category name can't be blank"
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    
    redirect_to categories_path
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = current_user.expenses.order('date desc')
  end
  
  def new
    @expense = Expense.new
    @categories = Category.categories_names
  end
  
  def create
    if params[:expense][:category].present?
      @category = current_user.build_category_if_not_exists(params[:expense][:category])
          
      @expense = current_user.expenses.build(expense_params)
      @expense.category = @category
    
      if @expense.save
        redirect_to expenses_path
      else
        flash[:alert] = "Fill in all fields please"
        render :new
      end
    else
      flash[:alert] = "Create a new category first"
      redirect_to new_category_path
    end
  end
  
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    
    redirect_to expenses_path
  end
  
  def edit
    @expense = Expense.find(params[:id])
  end
  
  def update
    @expense = Expense.find(params[:id])
    @category = current_user.build_category_if_not_exists(params[:expense][:category][:name])
    @expense.category = @category
    
    if @expense.update(expense_params)
      redirect_to expenses_path
    else
      flash[:alert] = "Fill in all fields please"
      render :edit
    end
  end
  
  private
  
  def expense_params
    params.require(:expense).permit(:sum, :date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def index
    @incomes = current_user.incomes.order('date desc')
  end

  def new
    @income = Income.new
    @categories = Category.categories_names
  end

  def create
    if params[:income][:category].present?
      @category = current_user.build_category_if_not_exists(params[:income][:category])
      
      @income = current_user.incomes.build(income_params)
      @income.category = @category

      if @income.save
        redirect_to incomes_path
      else
        flash[:alert] = "Fill in all fields please"
        render :new
      end
    else
      flash[:alert] = "Create a new category first"
      redirect_to new_category_path
    end
  end

  def destroy
    @income = Income.find(params[:id])
    @income.destroy
    
    redirect_to incomes_path
  end

  def edit
    @income = Income.find(params[:id])
  end

  def update
    @income = Income.find(params[:id])
    @category = current_user.build_category_if_not_exists(params[:income][:category][:name])
    @income.category = @category

    if @income.update(income_params)
      redirect_to incomes_path
    else
      flash[:alert] = "Fill in all fields please"
      render :edit
    end
  end

  private

  def income_params
    params.require(:income).permit(:sum, :date)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def report
      start_date  = params[:start_date].presence || 1.year.ago
      end_date    = params[:end_date].presence   || Time.now
      category_id = params[:category]
      
      @incomes  = current_user.filter_incomes(category_id, start_date, end_date)
      @expenses = current_user.filter_expenses(category_id, start_date, end_date)
            
      @incomes_sum  = @incomes.sum(:sum)
      @expenses_sum = @expenses.sum(:sum)
      
      @balance      = @incomes_sum - @expenses_sum
      @report_data  = (@incomes + @expenses).sort_by(&:date).reverse!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.text_field :name, placeholder: "Name", class: "form-control width-80" %>
  
  <%= f.submit nil, class: "btn btn-default width-80" %>
<% end %>

app/views/categories/edit.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 class="center">Edit category</h2>
  <%= render partial: "form" %>
  <%= render partial: "errors/error" %>
</div>

app/views/categories/index.html.erb
<br>
  <%= link_to "Add new Category", new_category_path, class: "btn btn-default btn-lg" %>
<br>

<table class="table table-striped">
  <% unless @categories.empty? %>
      <h2>Your categories:</h2>
  <% end %>
  
  <% @categories.each do |cat| %>
  <tr>
    <td><span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> <%= cat.name %></td>
    <td class="right">
      <%= link_to "Edit", edit_category_path(cat.id), class: "btn btn-warning btn-lg" %>
      <%= link_to "Delete", category_path(cat.id), method: :delete, data: {confirm: "Delete category?"}, class: "btn btn-danger btn-lg"%>
    </td>
  </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 class="center">Create new category</h2>
  <%= render partial: "form" %>
  <%= render partial: "errors/error" %>
</div>

app/views/expenses/_edit_form.html.erb
<%= form_for @expense do |f| %>
  <%= f.number_field :sum, placeholder: "Amount", class: "form-control width-80" %>
  <%= f.date_field :date, placeholder: "Date", class: "form-control width-80" %>
  <%= f.fields_for (@expense.category) do |ff| %>
    <%= ff.select(:name, options_from_collection_for_select(current_user.categories, "name", "name"),{}, {class: "form-control width-80"}) %>
  <% end %>
  <%= f.submit nil, class: "btn btn-default width-80" %>
<% end %>

app/views/expenses/_form.html.erb
<%= form_for @expense = Expense.new do |f| %>
  <%= f.number_field :sum, placeholder: "Amount", class: "form-control width-80" %>
  <%= f.date_field :date, placeholder: "Date", class: "form-control width-80" %>
  <%= f.select(:category, options_from_collection_for_select(current_user.categories, "name", "name"),{}, {class: "form-control width-80"}) %>
  <%= f.submit nil, class: "btn btn-default width-80" %>
<% end %>

app/views/expenses/edit.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 class="center">Edit expense</h2>
  <%= render partial: "edit_form" %>
  <%= render partial: "errors/error" %>
</div>

app/views/expenses/index.html.erb
<br>
<%= link_to "Add new Expense", new_expense_path, class: "btn btn-default btn-lg" %>
<br>

<table class="table table-striped">
  <% unless @expenses.empty? %>
    <h2>Your last expenses:</h2>
    <thead>
      <tr>
        <th>Category</th>
        <th>Amount</th>
        <th>Date</th>
        <th></th>
      </tr>
    </thead>
  <% end %>

  <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.category.name %></td>
      <td><%= number_to_currency(expense.sum, unit: "", precision: 0) %></td>
      <td><%= expense.date %></td>
      <td class="right">
        <%= link_to "Edit", edit_expense_path(expense.id), class: "btn btn-warning btn-lg" %>
        <%= link_to "Delete", expense_path(expense.id), method: :delete, data: {confirm: "Delete expense?"}, class: "btn btn-danger btn-lg"%>
      </td>
    </tr>
  <% end %>
</table>

app/views/expenses/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 class="center">Add new expense</h2>
  <%= render partial: "form" %>
  <%= render partial: "errors/error" %>
</div>

app/views/home/_navigation.html.erb
<% unless current_user %>
  <div class="col-md-offset-3 col-md-6">
    <ul class="nav nav-tabs authentication">
      <li class="item"><%= link_to "Sign Up", new_user_registration_path %></li>
      <li class="item"><%= link_to "Log In", new_user_session_path %></li>
    </ul>
  </div>
<% end %>

<% if current_user %>
  <ul class="nav nav-tabs navigation">
    <li class="item"><%= link_to "Expenses", expenses_path %></li>
    <li class="item"><%= link_to "Incomes", incomes_path %></li>
    <li class="item"><%= link_to "Categories", categories_path %></li>
    <li class="item"><%= link_to "Reports", report_path %></li>
  </ul>
<% end %>

app/views/home/index.html.erb
<% unless current_user %>
  <div class="col-md-offset-3 col-md-6 center">
    <h1>Sign in or Sign up</h1>
    <h2>And count your money!</h2>
  </div>
<% end %>

<% if current_user %>
  <ul class="col-md-offset-3 col-md-6 center">
    <h2>Hello, <%= current_user.email %>!</h2>
  </ul>
<% end %>

app/views/incomes/_edit_form.html.erb
<%= form_for @income do |f| %>
  <%= f.number_field :sum, placeholder: "Amount", class: "form-control width-80" %>
  <%= f.date_field :date, placeholder: "Date", class: "form-control width-80" %>
  <%= f.fields_for (@income.category) do |ff| %>
    <%= ff.select(:name, options_from_collection_for_select(current_user.categories, "name", "name"),{}, {class: "form-control width-80"}) %>
  <% end %>
  <%= f.submit nil, class: "btn btn-default width-80" %>
<% end %>

app/views/incomes/_form.html.erb
<%= form_for @income = Income.new do |f| %>
  <%= f.number_field :sum, placeholder: "Amount", class: "form-control width-80" %>
  <%= f.date_field :date, placeholder: "Date", class: "form-control width-80" %>
  <%= f.select(:category, options_from_collection_for_select(current_user.categories, "name", "name"),{}, {class: "form-control width-80"}) %>
  <%= f.submit nil, class: "btn btn-default width-80" %>
<% end %>

app/views/incomes/edit.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 class="center">Edit income</h2>
  <%= render partial: "edit_form" %>
  <%= render partial: "errors/error" %>
</div>

app/views/incomes/index.html.erb
<br>
<%= link_to "Add new Income", new_income_path, class: "btn btn-default btn-lg" %>
<br>

<table class="table table-striped">
  <% unless @incomes.empty? %>
    <h2>Your last incomes:</h2>
    <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th>Date</th>
      <th></th>
    </tr>
    </thead>
  <% end %>

  <% @incomes.each do |income| %>
    <tr>
      <td><%= income.category.name %></td>
      <td><%= number_to_currency(income.sum, unit: "", precision: 0) %></td>
      <td><%= income.date %></td>
      <td class="right">
        <%= link_to "Edit", edit_income_path(income.id), class: "btn btn-warning btn-lg" %>
        <%= link_to "Delete", income_path(income.id), method: :delete, data: {confirm: "Delete expense?"}, class: "btn btn-danger btn-lg"%>
      </td>
    </tr>
  <% end %>
</table>

app/views/incomes/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <h2 class="center">Add new income</h2>
  <%= render partial: "form" %>
  <%= render partial: "errors/error" %>
</div>

app/views/incomes/update.html.erb
<h1>Incomes#update</h1>
<p>Find me in app/views/incomes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IncomeTracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <div class="col-md-6 logo">
        <%= link_to image_tag("logo.png", size: "450x150"), root_path %>
      </div>
      
      <div class="col-md-6 user-info">
        <%= render partial: "/users/user_info" %>
      </div>
    </div>
  </div>
    
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <%= render partial: "/home/navigation" %>
      <%= yield %>
    </div>
  </div>

</body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>

app/views/reports/_form.html.erb
<%= form_tag(report_path, method: :get, class: "form-inline") do %>
  <div class="form-group">
  <%= date_field_tag :start_date, nil, class: "form-control" %>
  <%= date_field_tag :end_date, nil, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= select_tag :category, options_from_collection_for_select(current_user.categories, "id", "name"), include_blank: true, class: "form-control" %>
  <%= submit_tag "Show report", class: "btn btn-info" %>
  </div>
<% end %>

app/views/reports/report.html.erb
<br>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <ul class="nav nav-pills report-labels">
      <li class="item">Start date</li>
      <li class="item">End date</li>
      <li class="item">Category</li>
    </ul>
  </div>

</div>

<div class="row">
  <div class="col-md-offset-2 col-md-12">
    <%= render partial: "form" %>
  </div>
</div>

<br>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <table class="table">
      <tr>
        <td>Total incomes:</td> 
        <td style="color: green"><%= number_to_currency(@incomes_sum, unit: "", precision: 0) %></td>
      </tr>
      <tr>
        <td> Total expenses:</td>
        <td style="color: red"> <%= number_to_currency(@expenses_sum, unit: "", precision: 0) %></td>
      </tr>
      <tr>
        <td>Balance:</td> 
        <td style="color: <%= @balance > 0 ? "green" : "red" %>"><%= number_to_currency(@balance, unit: "", precision: 0) %></td>
      </tr>
    </table>
  </div>
</div>

<br>
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Category</th>
        <th>Amount</th>
        <th>Date</th>
      </tr>
      </thead>
    <% @report_data.each do |data|%>
      <tr style="color: <%= data.class == Expense ? "red" : "green"  %>">
        <td><%= data.category.name %></td>
        <td><%= number_to_currency(data.sum, unit: "", precision: 0) %></td>
        <td><%= data.date %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div> 

app/views/users/_user_info.html.erb
<% if current_user %>
  <br>
  <h1><%= current_user.email %></h1>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% end %>